var localization = {
	"english":
		{
			//Order of equipment is from internal game files, not necessarily the in-game order
			"sword0": "Heaven's Gate",
			"sword1": "Berzerker",
			"sword2": "Inferno",
			"sword3": "Ice Needle",
			"sword4": "Lightning Shard",
			"sword5": "Sapphire Saint",
			"sword6": "Black Fang",
			"sword7": "The Chopper",
			"sword8": "Giant Slayer",
			"sword9": "Hyper Drill",
			"sword10": "Emerald Smasher",
			"sword11": "Devil's Fork",
			"sword12": "Ultra Pro 9000X",
			"sword13": "Club of Withering",
			"sword14": "Crimson Razorback",
			"sword15": "Dragon's Feather",
			"sword16": "Golden Axe",
			"sword17": "Dark Stalker",
			"sword18": "Fusion Blade",
			"sword19": "Soul Eater",
			"sword20": "Love Blade",
			
			//Fun fact: The internal array for every staff in the game is called "STALVES".
			"staff0": "Sol Spear",
			"staff1": "Arctic Trident",
			"staff2": "Wrath of Zeus",
			"staff3": "Druid Staff",
			"staff4": "Nimbus Rod",
			"staff5": "Dragon Wings",
			"staff6": "Gigavolt",
			"staff7": "Alchemy Set",
			"staff8": "Kaladanda",
			"staff9": "Wrecking Rod",
			"staff10": "Elder's Wisdom",
			"staff11": "Obsidian Staff",
			"staff12": "Celtic Cross",
			"staff13": "Dark Tooth",
			"staff14": "The Knife",
			"staff15": "Paper Fan",
			"staff16": "Oak Staff",
			"staff17": "Beholding Eye",
			"staff18": "Soul Crusher",
			"staff19": "Shooting Star",
			"staff20": "Slime Staff",
			
			"gun0": "Nitro Bomber XL",
			"gun1": "Hellfire Shotgun",
			"gun2": "Thunder Core",
			"gun3": "Deep Blue",
			"gun4": "Chainsaw Gun",
			"gun5": "Vortex Cannon",
			"gun6": "Sub Zero",
			"gun7": "Shadow Blaster",
			"gun8": "Biohazard Blaster",
			"gun9": "Crystal Wing",
			"gun10": "Heavy Claw",
			"gun11": "Soul Pistol",
			"gun12": "Super Snipe ZX",
			"gun13": "Coconut Shooter",
			"gun14": "Flame Titan",
			"gun15": "Heartstopper",
			"gun16": "Gungnir",
			"gun17": "Spine Snapper",
			"gun18": "Desert Scorpion",
			"gun19": "Accelerator",
			"gun20": "Green Goliath",
			
			"bow0": "Fairy Bow",
			"bow1": "Cold Steel",
			"bow2": "Thor's Hammer",
			"bow3": "Aquamarine",
			"bow4": "Gaia's Gift",
			"bow5": "Crimson Dragon",
			"bow6": "Iron Tusk",
			"bow7": "Fenrir's Jaw",
			"bow8": "The Deceased",
			"bow9": "Juggernaught",
			"bow10": "Emerald Cyclone",
			"bow11": "Eagle Eye",
			"bow12": "The Stinger",
			"bow13": "Chieftain's Horns",
			"bow14": "Regal Turtle",
			"bow15": "Alchemist's Bow",
			"bow16": "Black Widow",
			"bow17": "Angel Wing",
			"bow18": "Sharanga",
			"bow19": "Earth's Whisper",
			"bow20": "Heaven's Voice",
			
			"toy0": "Steel Buckler",
			"toy1": "Bandit Blade",
			"toy2": "Neon Lightbulb",
			"toy3": "Honjo Masamune",
			"toy4": "Riot Shield",
			"toy5": "Leaf Shield",
			"toy6": "Star Hammer",
			"toy7": "Dog Sausage",
			"toy8": "Icecream Sandwich",
			"toy9": "Godly Book",
			"toy10": "Human Skull",
			"toy11": "Blood Bank",
			"toy12": "Viking Buckler",
			"toy13": "Turtle Shell",
			"toy14": "Elven Shield",
			"toy15": "Pixel Popper",
			"toy16": "Book of Spells",
			"toy17": "Power Paw",
			"toy18": "Devil's Sunrise",
			"toy19": "King's Guard",
			"toy20": "Buster Sword",
			
			"hatm0": "Captain's Hat",
			"hatm1": "Knight's Helmet",
			"hatm2": "Horned Helmet",
			"hatm3": "Spartan Helmet",
			"hatm4": "Genji Helmet",
			"hatm5": "Basket Hat",
			"hatm6": "Dragon Helmet",
			"hatm7": "Army Helmet",
			"hatm8": "Officer's Hat",
			"hatm9": "Space Helmet",
			"hatm10": "Scottish Cap",
			"hatm11": "Spelunking Hat",
			"hatm12": "Wizard Hat",
			"hatm13": "Headband",
			"hatm14": "Necromancer's Helmet",
			"hatm15": "Cardboard Box",
			"hatm16": "Gas Mask",
			"hatm17": "Death Mask",
			"hatm18": "Puppy Hat",
			"hatm19": "Pumpkin Head",
			"hatm20": "Santa Hat",
			
			"armorm0": "Captain's Coat",
			"armorm1": "Heroic Armor",
			"armorm2": "Viking Fur",
			"armorm3": "Spartan Cuirass",
			"armorm4": "Genji Armor",
			"armorm5": "Ninja Gear",
			"armorm6": "Dragon Armor",
			"armorm7": "Camo Jacket",
			"armorm8": "Officer's Coat",
			"armorm9": "Space Ace",
			"armorm10": "Scottish Kilt",
			"armorm11": "Explorer's Jacket",
			"armorm12": "Wizard Robe",
			"armorm13": "Turtle Gi",
			"armorm14": "Flame Suit",
			"armorm15": "Hobo Clothes",
			"armorm16": "Hipster Shirt",
			"armorm17": "Shell Armor",
			"armorm18": "Priest's Tunic",
			"armorm19": "Coat of Teeth",
			"armorm20": "Santa Outfit",
			
			//Fun fact: All of the "Bobble" hats are internally spelled "Bauble"! Except for the Spider Bobble. That one is spelled with bobble.
			"hatf0": "Red Ribbon",
			"hatf1": "Amber Bobble",
			"hatf2": "Nurse Hat",
			"hatf3": "Fur Hat",
			"hatf4": "Pope Hat",
			"hatf5": "Leafy Hairclip",
			"hatf6": "Curly Horns",
			"hatf7": "Cat Ears",
			"hatf8": "Flower Bobble",
			"hatf9": "Dark Bobble",
			"hatf10": "Slime Bunny",
			"hatf11": "Ninja Chopsticks",
			"hatf12": "Robot Ears",
			"hatf13": "Drill Bits",
			"hatf14": "Bunny Ears",
			"hatf15": "Ice Shards",
			"hatf16": "Royal Crown",
			"hatf17": "Rubber Duck",
			"hatf18": "Blue Elephant",
			"hatf19": "Spider Bobble",
			"hatf20": "Holly Hairpin",
			
			"armorf0": "Red Dress",
			"armorf1": "Ranger Skirt",
			"armorf2": "Nurse Uniform",
			"armorf3": "Fur Dress",
			"armorf4": "Pope Dress",
			"armorf5": "Cactus Dress",
			"armorf6": "Cow Costume",
			"armorf7": "Maid Outfit",
			"armorf8": "Summer Kimono",
			"armorf9": "Dark Gown",
			"armorf10": "Magical Skirt",
			"armorf11": "Ninja Skirt",
			"armorf12": "Mecha Suit",
			"armorf13": "Obsidian Armor",
			"armorf14": "School Uniform",
			"armorf15": "Bubble Dress",
			"armorf16": "Camo Skirt",
			"armorf17": "Sami Dress",
			"armorf18": "Casual Skirt",
			"armorf19": "Spider Gown",
			"armorf20": "Santa Skirt",
			
			//Fun fact: All the internal names for the earrings flairs are mispelled as "earings" in the game code!	
			"flair0": "Flame Badge",
			"flair1": "Lightning Badge",
			"flair2": "Frost Badge",
			"flair3": "Pearl Necklace",
			"flair4": "Surgical Mask",
			"flair5": "Angel Pin",
			"flair6": "Bandage",
			"flair7": "Iron Cross",
			"flair8": "Silver Cross",
			"flair9": "Golden Pendant",
			"flair10": "Battle Paint",
			"flair11": "Lucky Clover",
			"flair12": "Hoop Earings",
			"flair13": "The Tr*force",
			"flair14": "Green Cross",
			"flair15": "Fairy",
			"flair16": "Pocket Watch",
			"flair17": "Agnry Faic",
			"flair18": "Target Badge",
			"flair19": "Balance Badge",
			"flair20": "Tentacle",
			"flair21": "Peace Badge",
			"flair22": "Crossbone Pin",
			"flair23": "Chrome Earrings",
			"flair24": "Amethyst Earrings",
			"flair25": "Emerald Earrings",
			"flair26": "Fat Fly",
			"flair27": "Fake Mustache",
			"flair28": "Big Eyebrows",
			"flair29": "Small Cloud",
			"flair30": "Cat Tail",
			"flair31": "Mini Drone",
			"flair32": "Sword Medal",
			"flair33": "Shield Medal",
			"flair34": "Gold Star",
			"flair35": "Platinum Star",
			"flair36": "Heart Pendant",
			"flair37": "Lucky Fish",
			"flair38": "Coin Charm",
			"flair39": "Juicy Beast",
			"flair40": "The One R*ng",
			"flair41": "Baby Penguin",
			"flair42": "RAM Chip",
			"flair43": "Meow Meow Badge",
			"flair44": "Nano Machines",
			"flair45": "Pixel Glasses",
			"flair46": "Companion C*be",
			"flair47": "Dog Tags",
			"flair48": "Tetromino",
			"flair49": "Captain Viridian",
			"flair50": "Dinosaur Egg",
			"flair51": "Bitey Badge",
			"flair52": "Narutomaki",
			"flair53": "Pet Rock",
			"flair54": "Tooth",
			
			"equipEmpty": "Nothing",
			
			"pumpkin": "Pumpkin",
			"pineapple": "Pineapple",
			"watermelon": "Watermelon",
			"dragonfruit": "Dragon Fruit",
			"raspberries": "Raspberries",
			"blueberries": "Blueberries",
			"cloudberries": "Cloudberries",
			"garlic": "Garlic",
			"banana": "Banana",
			"pretzel": "Pretzel",
			"apple": "Apple",
			"cupcake": "Cupcake",
			"beer": "Beer",
			"cola": "Cola",
			"bru": "Iron Brew",
			"energy": "Energy Drink",
			"coffee": "Coffee",
			"espresso": "Espresso",
			"chili": "Chili Pepper",
			"orangejuice": "Orange Juice",
			"crisps": "Crisps",
			"chips": "Chips",
			"burger": "Hamburger",
			"pizza": "Pizza",
			
			//There are two copies of the throwable items. See the comment in fullItemList.js for more information.
			//You could probably remove the duplicates here, but I'm keeping them just to be safe.
			"snowball": "Snowball",
			"brick": "Brick",
			"shuriken": "Shuriken",
			"bomb": "Hand Bomb",
			
			"bacon": "Crispy Bacon",
			"beef": "Raw Beef",
			"chicken": "Chicken Leg",
			"egg": "Fried Egg",
			"poptart": "Poptart",
			"donut": "Donut",
			"cake": "Cake",
			"lollipop": "Lollipop",
			"bread": "Bread",
			"potato": "Potato",
			"pill": "Red Pill",
			"mushroom": "Mushroom",
			"turnip": "Turnip",
			"grapes": "Grapes",
			"mint": "Mint Leaf",
			"nut": "Hard Nut",
			"sushi": "Sushi",
			"riceball": "Riceball",
			"yoghurt": "Yoghurt",
			"milk": "Chocolate Milk",
			
			"snowball": "Snowball",
			"wool": "Wool",
			"brick": "Brick",
			"turd": "Earth Ball",
			"seashell": "Sea Shell",
			"cactus": "Cactus",
			"iron": "Iron Plate",
			"shuriken": "Shuriken",
			"feather": "White Feather",
			"flower": "Jungle Flower",
			"spring": "Spring",
			"wood": "Soft Wood",
			"bomb": "Hand Bomb",
			"herb": "An Herb",
			"pipe": "Copper Pipe",
			"tape": "Super Tape",
			"geode": "Geode",
			"root": "Gash Root",
			"powder": "Gunpowder",
			"glass": "Glass Shards",
			"fur": "Fine Fur",
			"butterflywing": "Butterfly Wing",
			"gems": "Rainbow Ore",
			"ice": "Liquid Ice",
			"water": "Solid Water",
			"buckle": "Belt Buckle",
			"steel": "Steel Plate",
			"magma": "Magma Chunk",
			"floppy": "Floppy",
			"silk": "Silk",
			"gear": "Metal Gear",
			"plastic": "Plastic",
			"amber": "Amber",
			"leather": "Leather",
			"virus": "Bio Virus",
			"claw": "Razor Claw",
			"rune2": "Sacred Rune",
			"spike": "Bone Spike",
			"silver": "Silver Plate",
			"satin": "Satin",
			"ruby": "Ruby",
			"topaz": "Topaz",
			"sapphire": "Sapphire",
			"emerald": "Emerald",
			"gold": "Gold Plate",
			"rune": "Dark Rune",
			"cpu": "P2 Processor",
			"kevlar": "Nano Fibre",
			"opal": "Opal",
			"lego": "Lecko Brick",
			"moonpearl": "Moon Pearl",
			"scales": "Dragon Scales",
			"gamechild": "Game Child",
			"titanium": "Titanium",
			"diamond": "Diamond",
			"darkmatter": "Dark Matter",
			"plutonium": "Plutonium Core",
			"grail": "The Holy Grail",
			"mythril": "Mythril Shards",
			"starfragment": "Star Fragment",
			
			"scouter": "Scouter",
			"oldboots": "Old Boots",
			"magneticboots": "Magnetic Boots",
			"leafyboots": "Leafy Boots",
			"spikedboots": "Spiked Boots",
			"thermalboots": "Thermal Boots",
			"wingedboots": "Winged Boots",
			"rubberboots": "Rubber Boots",
			"hammer": "The Hammer",
			"bighammer": "The Big Hammer",
			"axe": "The Axe",
			"shovel": "The Shovel",
			"stepladder": "The Stepladder",
			"raft": "The Raft",
			"candle": "The Candle",
			"fishingrod": "The Fishing Rod",
			"map": "World Map",
			"map2": "Red Envelope", //Red Envelope????
			"woodenkey": "Wooden Key",
			"coralkey": "Coral Key",
			"topazkey": "Topaz Key",
			"copperkey": "Copper Key",
			"goldkey": "Gold Key",
			"diamondkey": "Diamond Key",
			"flute": "Flute",
			"ocarina": "Ocarina",
			"starball": "Star Ball",
			"musicCD": "Music CD",
			"stick": "Stick",
			"plank": "Wooden Plank",
			"panties": "Panties",
			"stonehead": "Stone Head",
			"earthenware": "Earthenware",
			"newspaper": "Newspaper",
			"magazine": "Meow Magazine",
			"mail": "Snail Mail",
			"popcorn": "Popcorn",
			"keycard": "Golden Ticket", //yyyyyep
			"keycard2": "Green Keycard",
			"emptybottle": "Empty Bottle",
			"milkbottle": "Bottled Milk",
			"lavabottle": "Lava Sample",
			"waterbottle": "Holy Water",
			"darkbottle": "Evil Essence",
			"holybottle": "Fairy Dust",
			"sunglasses": "Sunglasses",
			"glasses": "Glasses",
			"sock1": "Left Sock",
			"sock2": "Right Sock",
			"headband": "Cool Headband",
			"battery": "Big Battery",
			"poop": "Turd",
			"cookie": "Cookie",
			"chocolate": "Chocolate",
			"earthorb": "Earth Orb",
			"windorb": "Wind Orb",
			"fireorb": "Fire Orb",
			"waterorb": "Water Orb",
			"greenjewel": "Emerald of Life",
			"bluejewel": "Sapphire of Dreams",
			"redjewel": "Ruby of Death",
			"halloweencandy": "Halloween Candy",
			"candycane": "Candy Cane",
			"valentine": "Heart Chocolate",
			"easteregg": "Easter Egg",
			"tomato": "Tomato",
			
			"invalid": "Invalid"
		}
}